---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: Hay dos formas de pagar las relaciones de sincronización después de que termine su prueba gratuita de 14 días. La primera opción es el pago por uso. La segunda opción consiste en comprar licencias directamente a NetApp. 
---
= Pague por las relaciones de sincronización una vez que finalice su prueba gratuita
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay dos formas de pagar las relaciones de sincronización después de que termine su prueba gratuita de 14 días. La primera opción es suscribirse a AWS o Azure para pagar por uso o anualmente. La segunda opción consiste en comprar licencias directamente a NetApp.

Puede suscribirse desde el AWS Marketplace o desde Azure Marketplace. No puede suscribirse de ambos.

Puede utilizar licencias de NetApp con una suscripción a Marketplace. Por ejemplo, si tiene 25 relaciones de sincronización, puede pagar las primeras 20 relaciones de sincronización con una licencia y, a continuación, pagar por el uso desde AWS o Azure con las 5 relaciones de sincronización restantes.

link:concept-licensing.html["Obtenga más información sobre cómo funcionan las licencias"].

Si usted no paga inmediatamente después de que su prueba gratuita termina, usted no podrá crear ninguna relación adicional. Las relaciones existentes no se eliminan, pero no puede realizar ningún cambio hasta que se suscriba o introduzca una licencia.

Las licencias deben gestionarse a través de la copia y sincronización de BlueXP o del sitio web correspondiente y *no* a través de una cartera digital.



== [[aws]]Suscribirse de AWS

AWS le permite pagar anualmente.

.De pago por uso
. En el menú de navegación de BlueXP , selecciona *Movilidad > Copiar y sincronizar*.
. Selecciona *Licencias*.
. Seleccione *AWS*.
. Seleccione *Suscribirse* y luego seleccione *Continuar*.
. Suscríbete en AWS Marketplace y, a continuación, vuelve a iniciar sesión en el servicio de copia y sincronización de BlueXP para completar el registro.
+
El siguiente vídeo muestra el proceso:

+
.Suscríbase a la copia y sincronización de BlueXP  desde AWS Marketplace
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.Pasos a pagar anualmente
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Vaya a la página AWS Marketplace"^].
. Seleccione *continuar para suscribirse*.
. Seleccione las opciones de contrato y luego seleccione *Crear contrato*.




== [[azure]]Suscribirse de Azure

Azure le permite pagar por uso o anualmente.

.Lo que necesitará
Cuenta de usuario de Azure con permisos de colaborador o propietario en la suscripción correspondiente.

.Pasos
. En el menú de navegación de BlueXP , selecciona *Movilidad > Copiar y sincronizar*.
. Selecciona *Licencias*.
. Seleccione *Azure*.
. Seleccione *Suscribirse* y luego seleccione *Continuar*.
. En el portal de Azure, selecciona *Crear*, selecciona tus opciones y luego selecciona *Suscribir*.
+
Seleccione *Mensual* para pagar por hora, o *Anual* para pagar por un año antes de la fecha.

. Una vez finalizada la implementación, seleccione el nombre del recurso de SaaS en la ventana emergente de notificaciones.
. Selecciona *Configurar cuenta* para volver a la copia y sincronización de BlueXP.
+
El siguiente vídeo muestra el proceso:

+
.Suscríbase a la copia y sincronización de BlueXP  desde Azure Marketplace
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[LICENCIAS]]Adquiera licencias de NetApp y añádalas a la copia y sincronización de BlueXP 

Para pagar por adelantado tus relaciones de sincronización, debes comprar una o más licencias y añadirlas al servicio de copia y sincronización de BlueXP.

.Lo que necesitará
Necesitará el número de serie de su licencia, así como el nombre de usuario y la contraseña de la cuenta del sitio de soporte de NetApp con la que está asociada la licencia.

.Pasos
. Adquiera una licencia por correo electrónico:ng-cloudsync-contact@netapp.com?Subject=Cloud%20Sync%20Service%20-%20BYOL%20Licencia%20Compra%20Solicite[Contacto con NetApp].
. En el menú de navegación de BlueXP , selecciona *Movilidad > Copiar y sincronizar*.
. Selecciona *Licencias*.
. Seleccione *Añadir licencia* y agregue la información requerida:
+
.. Introduzca el número de serie.
.. Seleccione la cuenta del sitio de soporte de NetApp asociada con la licencia que va a añadir:
+
*** Si su cuenta ya se ha añadido a BlueXP, selecciónela en la lista desplegable.
*** Si tu cuenta aún no se ha agregado, selecciona *Agregar Credenciales NSS*, introduce el nombre de usuario y la contraseña, selecciona *Registrar* y, a continuación, selecciónala en la lista desplegable.


.. Seleccione *Agregar*.






== Actualizar una licencia

Si ampliaste una licencia de copia y sincronización de BlueXP que compraste a NetApp, la nueva fecha de caducidad no se actualizará automáticamente en la copia y sincronización de BlueXP. Debe volver a agregar la licencia para actualizar la fecha de caducidad. Las licencias deben gestionarse a través de la copia y sincronización de BlueXP o del sitio web correspondiente y *no* a través de una cartera digital.

.Pasos
. En el menú de navegación de BlueXP , selecciona *Movilidad > Copiar y sincronizar*.
. Selecciona *Licencias*.
. Seleccione *Añadir licencia* y agregue la información requerida:
+
.. Introduzca el número de serie.
.. Seleccione la cuenta del sitio de soporte de NetApp asociada con la licencia que va a añadir.
.. Seleccione *Agregar*.




.Resultado
La copia y sincronización de BlueXP actualiza la licencia existente con la nueva fecha de vencimiento.
